FACEBOOK_APP_ID=tu_facebook_app_id
FACEBOOK_CLIENT_TOKEN=tu_facebook_client_token
GOOGLE_WEB_CLIENT_ID=1077576417175-8b3deus3foi11547ikbjr3plhoi52b6f.apps.googleusercontent.com
GOOGLE_SERVICES_JSON=ruta_al_archivo_google-services.json
GOOGLE_SERVICES_PLIST=ruta_al_archivo_GoogleService-Info.plist