package com.iyr.ultrachango

object Constants {
    val CURRENT_LOCATION = "CURRENT_LOCATION"
    val CURRENT_LOCATION_ID = "CURRENT_LOCATION_ID"
    val CURRENT_LOCATION_NAME = "CURRENT_LOCATION_NAME"
    val SECTION_SHOPPING_LIST = "SHOPPING_LIST"


    // Errors
    val ERROR_NO_LOCATION = "ERROR_NO_LOCATION"
    val PRODUCT_DOES_NOT_EXIST = "PRODUCT_DOES_NOT_EXIST"
}
